apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deploy
  namespace: helloworld
  labels:
    app: hello-world-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: helloworldapp
        image: 706949302588.dkr.ecr.ap-southeast-2.amazonaws.com/test-hello-world:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 512Mi
      securityContext:
        runAsUser: 1000
      imagePullSecrets:
      - name: aws-registry
