apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-svc
  name: hello-world-svc
  namespace: helloworld
spec:
  ports:
  - name: helloworld
    nodePort: 30423
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-app
  sessionAffinity: None
  type: LoadBalancer
